# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту kalashnikovaekaterina123@gmail.com(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -kalashnikovaekaterina123@gmail.com
    on_success: never # default: change
    on_failure: always # defa,,ult: always
    env:
      global:
        - CODECOV_TOKEN="4d47e578-b566-427a-9b06-a097edbac546"